# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'with.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 400)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(-30, -10, 851, 461))
        self.widget.setStyleSheet("background-color: rgb(55, 185, 200);\n"
"alternate-background-color: rgb(26, 159, 200);\n"
"alternate-background-color: rgb(85, 181, 200);")
        self.widget.setObjectName("widget")
        self.lcdNumber = QtWidgets.QLCDNumber(self.widget)
        self.lcdNumber.setGeometry(QtCore.QRect(310, 50, 171, 31))
        self.lcdNumber.setStyleSheet("color: rgb(132, 7, 7);\n"
"font: 75 12pt \"MS Serif\";\n"
"")
        self.lcdNumber.setObjectName("lcdNumber")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(70, 170, 71, 20))
        self.label.setStyleSheet("font: 75 italic 12pt \"Arial\";")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(160, 220, 75, 23))
        self.pushButton.setStyleSheet("font: 10pt \"Arial Rounded MT Bold\";")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(370, 220, 141, 31))
        self.label_2.setStyleSheet("font: 75 italic 12pt \"Arial\";")
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(520, 160, 141, 31))
        self.lineEdit.setStyleSheet("color: rgb(127, 18, 18);\n"
"font: 75 12pt \"MS Serif\";")
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(380, 280, 141, 31))
        self.label_3.setStyleSheet("font: 75 italic 12pt \"Arial\";")
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setGeometry(QtCore.QRect(500, 220, 111, 31))
        self.lineEdit_2.setStyleSheet("color: rgb(127, 18, 18);\n"
"font: 75 12pt \"MS Serif\";")
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(350, 160, 161, 31))
        self.label_4.setStyleSheet("font: 75 italic 12pt \"Arial\";\n"
"")
        self.label_4.setObjectName("label_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setGeometry(QtCore.QRect(470, 280, 111, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        self.lineEdit_3.setMaximumSize(QtCore.QSize(111, 31))
        self.lineEdit_3.setStyleSheet("color: rgb(127, 18, 18);\n"
"font: 75 12pt \"MS Serif\";\n"
"")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_4.setGeometry(QtCore.QRect(130, 170, 141, 21))
        self.lineEdit_4.setStyleSheet("font: 75 12pt \"MS Serif\";")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lcdNumber.raise_()
        self.label.raise_()
        self.pushButton.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.lineEdit_2.raise_()
        self.label_4.raise_()
        self.lineEdit.raise_()
        self.lineEdit_3.raise_()
        self.lineEdit_4.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Pays : "))
        self.pushButton.setText(_translate("Dialog", "Click"))
        self.label_2.setText(_translate("Dialog", "Temperature :"))
        self.label_3.setText(_translate("Dialog", "Humidity :"))
        self.label_4.setText(_translate("Dialog", "weather_descrption :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
